### DISCUSSION TITLE
카프카 클러스터 도커로 콘솔 컨슈머, 프로듀서 테스트

### DISCUSSION THREAD

**Discussion by Kdreamtomaster** [DEProjTeam07/coc-pipeline#12] [Show and tell]
#4 

## 컨테이너 오케스트레이션 툴 없이 카프카 클러스터 만들기 

> 설정에 퍼블릭 아이피 쓰면, 아무리 보안그룹 뚫어놔도 콘솔 프로듀서 실행시에 문제가 생겼음(리더 선출에서 에러생김). 프라이빗 아이피 쓸것

```
>[2024-09-03 12:20:13,380] WARN [Producer clientId=console-producer] Got error produce response with correlation id 6 on topic-partition test-2, retrying (2 attempts left). Error: NOT_LEADER_OR_FOLLOWER (org.apache.kafka.clients.producer.internals.Sender)
[2024-09-03 12:20:13,381] WARN [Producer clientId=console-producer] Received invalid metadata error in produce request on partition test-2 due to org.apache.kafka.common.errors.NotLeaderOrFollowerException: For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
```

### server01  .env
```bash
KAFKA_KRAFT_MODE=true
CLUSTER_ID=${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}
KAFKA_LISTENER_NAME=PLAINTEXT
KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.31.3.183:9092
KAFKA_PROCESS_ROLES=broker,controller
KAFKA_NODE_ID=1
KAFKA_CONTROLLER_QUORUM_VOTERS=1@172.31.3.183:9093,2@172.31.2.37:9093,3@172.31.0.17:9093
KAFKA_LOG_DIRS=/var/lib/kafka/data
KAFKA_LOG_RETENTION_HOURS=168
KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
```

### server02  .env
```bash
KAFKA_KRAFT_MODE=true
CLUSTER_ID=${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}
KAFKA_LISTENER_NAME=PLAINTEXT
KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.31.2.37:9092
KAFKA_PROCESS_ROLES=broker,controller
KAFKA_NODE_ID=2
KAFKA_CONTROLLER_QUORUM_VOTERS=1@172.31.3.183:9093,2@172.31.2.37:9093,3@172.31.0.17:9093
KAFKA_LOG_DIRS=/var/lib/kafka/data
KAFKA_LOG_RETENTION_HOURS=168
KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
```

### server03  .env

```bash
KAFKA_KRAFT_MODE=true
CLUSTER_ID=${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}
KAFKA_LISTENER_NAME=PLAINTEXT
KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.31.0.17:9092
KAFKA_PROCESS_ROLES=broker,controller
KAFKA_NODE_ID=3
KAFKA_CONTROLLER_QUORUM_VOTERS=1@172.31.3.183:9093,2@172.31.2.37:9093,3@172.31.0.17:9093
KAFKA_LOG_DIRS=/var/lib/kafka/data
KAFKA_LOG_RETENTION_HOURS=168
KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
```

### docker-compose.yml

```yaml
services:
  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    extra_hosts:
      - "server01:172.31.3.183"
      - "server02:172.31.2.37"
      - "server03:172.31.0.17"

    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - .env
    user: "1000:1000"
    volumes:
      - kafka_volume:/var/lib/kafka/data
volumes:
  kafka_volume:
    driver: local
```

### 서버 1 컨테이너에서 토픽 생성및 콘솔 프로듀서로 인입

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/2f8a8e3b-8072-4f9d-98a3-e24d3180ea8e">

### 서버 3 컨테이너에서 컨슈머로 데이터 출력 확인

<img width="572" alt="image" src="https://github.com/user-attachments/assets/70554d7c-81ea-4cd3-8e66-c996548b6d9e">

각 서버 

```
cd ~/app/kafka-docker  
docker compose up
```

각 서버 에서 

`docker exec -it kafka bash`

> 테스트 명령어

```
kafka-topics --create --bootstrap-server server01:9092,server02:9092,server03:9092 --replication-factor 3 --partitions 3 --topic test
```

```
kafka-topics --list --bootstrap-server server01:9092,server02:9092,server03:9092
```

```
kafka-console-producer --broker-list server01:9092,server02:9092,server03:9092 --topic test
```

```
kafka-console-consumer --bootstrap-server server01:9092,server02:9092,server03:9092  --topic test --from-beginning
```

**Comment by wwkler** [comment]
존경합니다 형님

**Comment by Kdreamtomaster** [comment]
volume 붙인뒤 컨테이너 삭제후 재기동해도 토픽 리스트 남아있고 콘솔 프로듀서, 컨슈머 정상 작동하는거 확인하였습니다.

<img width="436" alt="image" src="https://github.com/user-attachments/assets/92434d46-eba2-4607-bf2e-d5b3180c9efc">
<img width="493" alt="image" src="https://github.com/user-attachments/assets/82fe0335-a9de-4db6-a4fa-7b85bbf7df05">
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/3c4c8057-baa2-48e2-a556-fa88b0981578">

**Comment by Kdreamtomaster** [comment]
#4 
#18 
## 테스트 

### ~/app/kafka-docker 에서 테스트 진행중


### 혹시나 스파크 쪽 에러가 카프카 자원 제한을 안 걸어 생기는게 아닐까 생각이 들어 CPU,Memory 관련 옵션 수정하고자 합니다.

## .env 쪽 아래 한줄 추가  최소 힙 1기가 최대 2기가
```
KAFKA_HEAP_OPTS: "-Xmx2G -Xms1G"
```


## docker-compose.yaml
- services 하위에 volumes 밑에 아래부분 추가.
```
    deploy:
      resources:
        limits:
          memory: 4g      # Kafka 컨테이너의 메모리 제한을 4GB로 설정
          cpus: "2.0"     # CPU 제한: 최대 2개의 CPU 코어를 사용
        reservations:
          memory: 2g      # 최소 2GB 메모리 예약
          cpus: "1.0"     # 최소 1개의 CPU 코어 예약
```
