### DISCUSSION TITLE
Docker Host Network로 Spark Cluster 사용하기

### DISCUSSION THREAD

**Discussion by wwkler** [DEProjTeam07/coc-pipeline#24] [Show and tell]
## Docker Host Network로 Spark Cluster 사용하기 

- 구성도 
<img width="674" alt="스크린샷 2024-09-09 오후 2 58 56" src="https://github.com/user-attachments/assets/8b4cb6a5-c17a-4e27-89ce-ea9c606ece23">

    - 컨테이너 IP는 로컬(호스트) IP와 똑같으며 
    - 컨테이너에서 7077번 포트를 쓰는 것은 로컬(호스트)의 7077번 포트를 쓰는 것이다. 
    - 결론은 컨테이너와 로컬(호스트)는 네트워크적으로 통합되어 있고 환경 측면에서는 분리되어 있다 . 

<br>
<br>

- 서버 1: Dockerfile 

```
  # 베이스 이미지로 bitnami/spark:3.5.1 사용
  FROM bitnami/spark:3.5.1
  
  # root 사용자 권한으로 전환
  USER root
  
  # 필요한 패키지 설치 (curl, wget, ping, net-tools 등) 및 boto3 설치
  RUN apt-get update && \
      apt-get install -y curl wget iputils-ping net-tools && \
      pip install boto3
  
  # Kafka와 연동하기 위한 JAR 파일들을 wget으로 다운로드
  RUN wget -P /opt/bitnami/spark/jars \
      https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar && \
      wget -P /opt/bitnami/spark/jars \
      https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.0/kafka-clients-3.5.0.jar && \
      wget -P /opt/bitnami/spark/jars \
      https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.0/commons-pool2-2.11.0.jar && \
      wget -P /opt/bitnami/spark/jars \
      https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/3.2.6/metrics-core-3.2.6.jar && \
      wget -P /opt/bitnami/spark/jars \
      https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.1/spark-token-provider-kafka-0-10_2.12-3.5.1.jar
  
  # 작업 디렉토리를 /opt/bitnami/spark으로 설정
  WORKDIR /opt/bitnami/spark
```
<br>

- 서버 1 : Dockerfile을 바탕으로 docker-compose.yaml 구성

<br>

```
  version: '3.8'
  services: 
    spark-master:
      build: 
        context: .  
        dockerfile: Dockerfile 
      container_name: spark-master
      environment:
        - SPARK_MODE=master
        - SPARK_MASTER_HOST={{Server 1 Private IP}}
        - SPARK_MASTER_WEBUI_PORT=8085
        - SPARK_MASTER_PORT=7077
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
        - SPARK_USER=spark
      volumes:
        - ./test:/opt/bitnami/spark/test
        - ./dev:/opt/bitnami/spark/dev
      restart: always
      network_mode: "host"
```
<br>
<br>

- 서버 2: docker-compose.yaml 

<br>

```
  version: '3.8'
  services:
    spark-worker-1:
      image: bitnami/spark:3.5.1  # 안정적인 Spark 3.5.1 버전 사용
      container_name: spark-worker-1
      user: "root"   # root 사용자로 실행
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_HOST={{Server 1 Private IP}}:7077  # Server 1에 대한 private ip 
        - SPARK_MASTER_URL=spark://{{Server 1 Private IP}}:7077 # Server 1에 대한 private ip 
        - SPARK_WORKER_MEMORY=8G
        - SPARK_WORKER_CORES=2
        - SPARK_WORKER_WEBUI_PORT=8086
        - SPARK_WORKER_PORT=18081 # Worker 포트는 Random이여서 18081로 고정
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
        - SPARK_USER=spark
      restart: always  # 중단 시 자동으로 재시작
      deploy:
        resources:
          limits:
            cpus: "2.0"
            memory: "8G"
      network_mode: "host"
```

<br> 

- 서버 3 : docker-compose.yaml 

<br> 

```
  version: '3.8'
  services:
  spark-worker-2:
    image: bitnami/spark:3.5.1  # 안정적인 Spark 3.5.1 버전 사용
    container_name: spark-worker-2
    user: "root"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST={{Server 1 Private IP}}:7077 # Server 1 private ip 
      - SPARK_MASTER_URL=spark://{{Server 1 Private IP}}7077 # Server 1 private ip 
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_WEBUI_PORT=8087
      - SPARK_WORKER_PORT=18081 # Worker 포트는 랜덤이여서 18081로 고정 
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    restart: always  # 중단 시 자동으로 재시작
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "8G"
    network_mode: "host"
```
<br>
<br>

- kafka와 연동 
  - 명령어 

```
# 명령어 
root@ip-172-31-3-183:/opt/bitnami/spark# ./bin/spark-submit --master spark://{{Server 1 Private IP}}:7077 /opt/bitnami/spark/test/test.py
```
<br>

- kafka와 연동
   - test.py
```
 # Kafka와 연동하는 test.py 
  from pyspark.sql import SparkSession 
  from pyspark.sql.functions import col
  
  # SparkSession 만들기 
  spark = SparkSession \
          .builder \
          .appName("kafka_consumer_test") \
          .config("spark.driver.host", "{{Server 1 Private IP }}") \
          .config("spark.driver.bindAddress", "0.0.0.0") \
          .config("spark.driver.port", "7077") \
          .config("spark.executor.instances", "2") \
          .config("spark.jars", "/opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.5.0.jar,"
                                "/opt/bitnami/spark/jars/kafka-clients-3.5.0.jar,"
                                "/opt/bitnami/spark/jars/commons-pool2-2.11.0.jar,"
                                "/opt/bitnami/spark/jars/metrics-core-3.2.6.jar,"
                                "/opt/bitnami/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar") \
          .master("spark://{{Server 1 Private IP}}:7077") \
          .getOrCreate()
          
  # Kafka 설정값 
  topic_name = "test"
  bootstrap_servers = "{{Server 1 Private IP}}:9092,{{Server 2 Private IP}}:9092,{{Server 3 Private IP}}:9092"
  
  # spark가 kafka에 있는 데이터 consuming 
  kafka_df = spark \
              .read \
              .format("kafka") \
              .option("kafka.bootstrap.servers", bootstrap_servers) \
              .option("subscribe", topic_name) \
              .option("startingOffsets", "earliest") \
              .load()
  
  # value가 binary 데이터를 디코딩해서 출력    
  kafka_df_converted = kafka_df.withColumn("value", col("value").cast("string"))
  
  total_rows = kafka_df_converted.count()
  
  kafka_df_converted.select("key", "value", "topic", "partition", "offset").show(total_rows, truncate=False)
 
```
<br>

- kafka와 연동
   - 결과 
```
# 결과 
|key |value|topic|partition|offset|
+----+-----+-----+---------+------+
|NULL|1    |test |0        |0     |
|NULL|2    |test |0        |1     |
|NULL|3    |test |0        |2     |
|NULL|4    |test |0        |3     |
|NULL|5    |test |0        |4     |
|NULL|6    |test |0        |5     |
|NULL|1    |test |0        |6     |
|NULL|2    |test |0        |7     |
|NULL|3    |test |0        |8     |
|NULL|1    |test |0        |9     |
|NULL|2    |test |0        |10    |
|NULL|3    |test |0        |11    |
|NULL|1    |test |0        |12    |
|NULL|2    |test |0        |13    |
|NULL|3    |test |0        |14    |
|NULL|2    |test |0        |15    |
|NULL|2    |test |0        |16    |
|NULL|6    |test |0        |17    |
|NULL|2    |test |0        |18    |
|NULL|3    |test |0        |19    |
|NULL|4    |test |0        |20    |
|NULL|5    |test |0        |21    |
|NULL|6    |test |0        |22    |
|NULL|7    |test |0        |23    |
|NULL|2    |test |0        |24    |
|NULL|3    |test |0        |25    |
|NULL|4    |test |0        |26    |
|NULL|5    |test |0        |27    |
|NULL|6    |test |0        |28    |
|NULL|7    |test |0        |29    |
|NULL|3    |test |0        |30    |
|NULL|4    |test |0        |31    |
|NULL|5    |test |0        |32    |
|NULL|6    |test |0        |33    |
|NULL|7    |test |0        |34    |
|NULL|1    |test |0        |35    |
|NULL|2    |test |0        |36    |
|NULL|3    |test |0        |37    |
|NULL|4    |test |0        |38    |
|NULL|5    |test |0        |39    |
|NULL|6    |test |0        |40    |
|NULL|7    |test |0        |41    |
|NULL|1    |test |0        |42    |
|NULL|7    |test |0        |43    |
|NULL|1    |test |0        |44    |
|NULL|2    |test |0        |45    |
|NULL|4    |test |0        |46    |
|NULL|5    |test |0        |47    |
|NULL|6    |test |0        |48    |
|NULL|7    |test |0        |49    |
|NULL|1    |test |0        |50    |
|NULL|2    |test |0        |51    |
|NULL|3    |test |0        |52    |
|NULL|4    |test |0        |53    |
|NULL|5    |test |0        |54    |
|NULL|6    |test |0        |55    |
|NULL|7    |test |0        |56    |
|NULL|1    |test |0        |57    |
|NULL|2    |test |0        |58    |
|NULL|3    |test |0        |59    |
|NULL|4    |test |0        |60    |
|NULL|5    |test |0        |61    |
|NULL|6    |test |0        |62    |
|NULL|7    |test |0        |63    |
|NULL|1    |test |0        |64    |
|NULL|2    |test |0        |65    |
|NULL|3    |test |0        |66    |
|NULL|4    |test |0        |67    |
|NULL|5    |test |0        |68    |
|NULL|6    |test |0        |69    |
|NULL|7    |test |0        |70    |
|NULL|1    |test |0        |71    |
|NULL|2    |test |0        |72    |
|NULL|3    |test |0        |73    |
|NULL|4    |test |0        |74    |
|NULL|5    |test |0        |75    |
|NULL|6    |test |0        |76    |
|NULL|7    |test |0        |77    |
|NULL|1    |test |0        |78    |
|NULL|2    |test |0        |79    |
|NULL|3    |test |0        |80    |
|NULL|4    |test |0        |81    |
|NULL|5    |test |0        |82    |
|NULL|6    |test |0        |83    |
|NULL|7    |test |0        |84    |
|NULL|1    |test |0        |85    |
|NULL|2    |test |0        |86    |
|NULL|3    |test |0        |87    |
|NULL|4    |test |0        |88    |
|NULL|5    |test |0        |89    |
|NULL|6    |test |0        |90    |
|NULL|7    |test |0        |91    |
|NULL|3    |test |0        |92    |
|NULL|4    |test |0        |93    |
|NULL|5    |test |0        |94    |
|NULL|6    |test |0        |95    |
|NULL|7    |test |0        |96    |
|NULL|1    |test |0        |97    |
|NULL|5    |test |0        |98    |
|NULL|2    |test |0        |99    |
|NULL|3    |test |0        |100   |
|NULL|4    |test |0        |101   |
|NULL|5    |test |0        |102   |
|NULL|6    |test |0        |103   |
|NULL|7    |test |0        |104   |
|NULL|1    |test |0        |105   |
|NULL|2    |test |0        |106   |
|NULL|3    |test |0        |107   |
|NULL|1    |test |1        |0     |
|NULL|5    |test |1        |1     |
|NULL|4    |test |1        |2     |
|NULL|1    |test |1        |3     |
|NULL|5    |test |1        |4     |
|NULL|6    |test |1        |5     |
|NULL|1    |test |1        |6     |
|NULL|2    |test |1        |7     |
|NULL|2    |test |1        |8     |
|NULL|3    |test |1        |9     |
|NULL|2    |test |1        |10    |
|NULL|4    |test |1        |11    |
|NULL|7    |test |1        |12    |
|NULL|1    |test |1        |13    |
|NULL|2    |test |1        |14    |
|NULL|3    |test |1        |15    |
|NULL|4    |test |1        |16    |
|NULL|5    |test |1        |17    |
|NULL|6    |test |1        |18    |
|NULL|7    |test |1        |19    |
|NULL|1    |test |1        |20    |
|NULL|3    |test |1        |21    |
|NULL|4    |test |1        |22    |
|NULL|7    |test |1        |23    |
|NULL|1    |test |1        |24    |
|NULL|2    |test |1        |25    |
|NULL|3    |test |1        |26    |
|NULL|4    |test |1        |27    |
|NULL|5    |test |1        |28    |
|NULL|6    |test |1        |29    |
|NULL|7    |test |1        |30    |
|NULL|1    |test |1        |31    |
|NULL|4    |test |1        |32    |
|NULL|6    |test |1        |33    |
|NULL|3    |test |2        |0     |
|NULL|4    |test |2        |1     |
|NULL|6    |test |2        |2     |
|NULL|7    |test |2        |3     |
|NULL|1    |test |2        |4     |
|NULL|3    |test |2        |5     |
|NULL|5    |test |2        |6     |
|NULL|7    |test |2        |7     |
|NULL|1    |test |2        |8     |
|NULL|2    |test |2        |9     |
|NULL|3    |test |2        |10    |
|NULL|4    |test |2        |11    |
|NULL|7    |test |2        |12    |
|NULL|1    |test |2        |13    |
|NULL|4    |test |2        |14    |
|NULL|5    |test |2        |15    |
|NULL|6    |test |2        |16    |
|NULL|3    |test |2        |17    |
|NULL|3    |test |2        |18    |
|NULL|5    |test |2        |19    |
|NULL|6    |test |2        |20    |
|NULL|1    |test |2        |21    |
|NULL|2    |test |2        |22    |
|NULL|2    |test |2        |23    |
|NULL|6    |test |2        |24    |
|NULL|5    |test |2        |25    |
|NULL|7    |test |2        |26    |
+----+-----+-----+---------+------+

```
