### DISCUSSION TITLE
Promethus-Grafana 모니터링 PromQL 작성 예시 모음

### DISCUSSION THREAD

**Discussion by Kdreamtomaster** [DEProjTeam07/coc-pipeline#41] [General]
# Kafka

### 질문
Prometheus Kafka 관련 Grafana 대시보드용 PromQL 작성 방법

### 답변
Kafka 메트릭을 Prometheus와 Grafana를 사용하여 모니터링하기 위해 PromQL 쿼리를 작성하는 방법은 다음과 같습니다:

## **1. Prometheus와 Grafana 설정**

- **JMX Exporter 설치**: 먼저 Kafka 메트릭이 JMX Exporter를 통해 노출되도록 설정해야 합니다. JMX Exporter의 GitHub 페이지에서 `yml` 파일 예제를 참고하여 Kafka 메트릭을 Prometheus에 노출하도록 구성합니다.

- **Prometheus 구성**: `prometheus.yml` 설정 파일에 Kafka 타겟을 추가합니다. 여기에는 Kafka 브로커와 Zookeeper 인스턴스의 주소 및 잡 이름 설정이 포함됩니다.

- **Grafana에서 Prometheus 데이터 소스 추가**: Grafana에 로그인하여 Configuration > Data Sources로 이동한 후 Prometheus를 데이터 소스로 추가합니다.

## **2. PromQL 쿼리 작성**

설정이 완료되면 Grafana에서 Kafka 메트릭을 시각화하기 위한 PromQL 쿼리를 작성할 수 있습니다. 다음은 일반적인 Kafka 메트릭과 해당하는 PromQL 쿼리 예시입니다:

- **CPU 사용량**:
  ```promql
  rate(process_cpu_seconds_total{job="kafka"}[5m])
  ```

- **JVM 메모리 사용량**:
  ```promql
  jvm_memory_bytes_used{job="kafka"}
  ```

- **토픽별 메시지 수**:
  ```promql
  sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job="kafka"}[5m])) by (topic)
  ```

- **토픽별 입력 바이트 수**:
  ```promql
  sum(rate(kafka_server_brokertopicmetrics_bytesin_total{job="kafka"}[5m])) by (topic)
  ```

- **토픽별 출력 바이트 수**:
  ```promql
  sum(rate(kafka_server_brokertopicmetrics_bytesout_total{job="kafka"}[5m])) by (topic)
  ```

## **3. Grafana 대시보드 생성**

- **사전 구성된 대시보드 가져오기**: Grafana Labs나 다른 소스에서 사전 구성된 대시보드를 가져올 수 있습니다. 예를 들어, Grafana Labs에서 제공하는 Kafka Metrics 대시보드는 게이지, 그래프, 테이블과 같은 다양한 패널을 사용하여 메트릭을 표시합니다.

- **시각화 사용자 정의**: 가져온 대시보드를 기반으로 필요에 따라 새로운 패널을 추가하거나 기존 패널을 수정하여 작성한 PromQL 쿼리를 적용할 수 있습니다.

이러한 과정을 통해 Prometheus와 Grafana를 사용하여 Kafka 클러스터를 효과적으로 모니터링하고, 사용자 정의된 PromQL 쿼리를 통해 대시보드에 데이터를 시각화할 수 있습니다. 이를 통해 주요 성능 지표를 추적하고 Kafka 인프라의 상태를 확인할 수 있습니다.

**Comment by Kdreamtomaster** [comment]
# Airflow 

Apache Airflow의 메트릭을 Prometheus와 Grafana를 사용하여 모니터링하기 위한 PromQL 쿼리를 작성하는 방법은 다음과 같습니다:

## **1. Airflow, Prometheus 및 Grafana 설정**

- **Airflow Prometheus Exporter 설치**: Airflow 메트릭을 Prometheus로 보내기 위해 `airflow-prometheus-exporter`를 설치합니다. 이 플러그인은 Airflow의 스케줄러, DAG, 태스크에 대한 다양한 메트릭을 노출합니다[1].

- **StatsD Exporter 사용**: Airflow는 StatsD 프로토콜을 사용하여 메트릭을 전송할 수 있습니다. StatsD Exporter를 사용하여 이 메트릭을 Prometheus 형식으로 변환하고 Prometheus 서버가 이를 스크랩하도록 설정합니다[2][5].

- **Prometheus 설정**: `prometheus.yml` 파일에 Airflow 메트릭을 수집할 수 있도록 설정합니다. 예를 들어:
  ```yaml
  scrape_configs:
    - job_name: 'airflow'
      static_configs:
        - targets: ['localhost:9102']
  ```

- **Grafana에서 Prometheus 데이터 소스 추가**: Grafana에 로그인하여 Data Sources에서 새로운 데이터 소스로 Prometheus를 추가합니다[5].

## **2. PromQL 쿼리 작성**

이제 Grafana 대시보드에서 사용할 수 있는 몇 가지 기본적인 PromQL 쿼리 예제를 소개합니다:

- **태스크 상태 모니터링**:
  ```promql
  sum(airflow_task_status{status="success"}) by (dag_id, task_id)
  ```
  이 쿼리는 DAG 및 태스크 ID별로 성공한 태스크의 수를 보여줍니다.

- **스케줄러 하트비트**:
  ```promql
  rate(airflow_scheduler_heartbeat{job="airflow"}[5m])
  ```
  이 쿼리는 스케줄러의 하트비트를 모니터링합니다.

- **태스크 실패 수**:
  ```promql
  sum(airflow_task_status{status="failed"}) by (dag_id, task_id)
  ```
  DAG 및 태스크 ID별로 실패한 태스크의 수를 보여줍니다.

## **3. Grafana 대시보드 생성**

- **대시보드 구성**: 위의 PromQL 쿼리를 사용하여 Grafana에서 새로운 패널을 추가하고 시각화를 구성합니다. 각 패널은 특정 메트릭을 시각화하는 데 사용됩니다.

- **커스터마이징**: 필요에 따라 대시보드를 커스터마이징하여 추가적인 메트릭이나 시각화 스타일을 적용할 수 있습니다.

이 과정을 통해 Apache Airflow의 성능과 상태를 효과적으로 모니터링할 수 있으며, Grafana 대시보드를 통해 실시간으로 데이터를 시각화할 수 있습니다.

Citations:
[1] https://pypi.org/project/airflow-prometheus-exporter/
[2] https://www.redhat.com/en/blog/monitoring-apache-airflow-using-prometheus
[3] https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/metrics.html
[4] https://spidyweb.tistory.com/540
[5] https://wooono.tistory.com/767

**Comment by Kdreamtomaster** [comment]
# Spark

Apache Spark의 메트릭을 Prometheus와 Grafana를 사용하여 모니터링하기 위한 PromQL 쿼리를 작성하는 방법은 다음과 같습니다:

## **1. Spark, Prometheus 및 Grafana 설정**

- **Spark 설정**: Spark의 `metrics.properties` 파일을 설정하여 Prometheus와 통합합니다. 이 파일은 `$SPARK_CONF_DIR`에 위치하며, 다음과 같이 설정할 수 있습니다:

  ```plaintext
  *.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
  *.sink.prometheusServlet.path=/metrics/prometheus
  master.sink.prometheusServlet.path=/metrics/master/prometheus
  applications.sink.prometheusServlet.path=/metrics/applications/prometheus
  ```

- **Prometheus 설정**: Prometheus의 `prometheus.yml` 파일에 Spark 메트릭을 수집할 수 있도록 엔드포인트를 추가합니다.

- **Grafana 데이터 소스 추가**: Grafana에서 Prometheus를 데이터 소스로 추가합니다. Grafana UI에서 "Data Sources" 메뉴를 선택하고 Prometheus 서버 정보를 입력하여 연결을 테스트합니다[1][2].

## **2. PromQL 쿼리 작성**

Grafana 대시보드에서 사용할 수 있는 몇 가지 기본적인 PromQL 쿼리 예제는 다음과 같습니다:

- **JVM 메모리 사용량**:
  ```promql
  jvm_memory_bytes_used{job="spark"}
  ```
  이 쿼리는 Spark JVM의 메모리 사용량을 모니터링합니다.

- **실행 중인 태스크 수**:
  ```promql
  sum(spark_executor_runningTasks{job="spark"})
  ```
  이 쿼리는 현재 실행 중인 Spark 태스크의 총 수를 보여줍니다.

- **CPU 사용량**:
  ```promql
  rate(spark_executor_cpuTime{job="spark"}[5m])
  ```
  이 쿼리는 Spark 실행자의 CPU 사용량을 모니터링합니다.

## **3. Grafana 대시보드 생성**

- **대시보드 구성**: 위의 PromQL 쿼리를 사용하여 Grafana에서 새로운 패널을 추가하고 시각화를 구성합니다. 각 패널은 특정 메트릭을 시각화하는 데 사용됩니다.

- **커스터마이징**: 필요에 따라 대시보드를 커스터마이징하여 추가적인 메트릭이나 시각화 스타일을 적용할 수 있습니다.

이 과정을 통해 Apache Spark의 성능과 상태를 효과적으로 모니터링할 수 있으며, Grafana 대시보드를 통해 실시간으로 데이터를 시각화할 수 있습니다.

Citations:
[1] https://github.com/cerndb/spark-dashboard
[2] https://learn.microsoft.com/ko-kr/azure/synapse-analytics/spark/use-prometheus-grafana-to-monitor-apache-spark-application-level-metrics
[3] https://community.cloudera.com/t5/Community-Articles/Monitoring-Spark-2-performance-via-Grafana-in-Ambari-Metrics/ta-p/248991
[4] https://danawalab.github.io/common/2020/03/17/Common-Dashboard.html
[5] https://jason-heo.github.io/bigdata/2021/01/31/spark30-prometheus.html

**Reply by Kdreamtomaster** [reply]
## spark metric 관련 조사
Executor Level Metric name | Short description
-- | --
rddBlocks | RDD blocks in the block manager of this executor.
memoryUsed | Storage memory used by this executor.
diskUsed | Disk space used for RDD storage by this executor.
totalCores | Number of cores available in this executor.
maxTasks | Maximum number of tasks that can run concurrently in this executor.
activeTasks | Number of tasks currently executing.
failedTasks | Number of tasks that have failed in this executor.
completedTasks | Number of tasks that have completed in this executor.
totalTasks | Total number of tasks (running, failed and completed) in this executor.
totalDuration | Elapsed time the JVM spent executing tasks in this executor. The value is expressed in milliseconds.
totalGCTime | Elapsed time the JVM spent in garbage collection summed in this executor. The value is expressed in milliseconds.
totalInputBytes | Total input bytes summed in this executor.
totalShuffleRead | Total shuffle read bytes summed in this executor.
totalShuffleWrite | Total shuffle write bytes summed in this executor.
maxMemory | Total amount of memory available for storage, in bytes.
memoryMetrics.* | Current value of memory metrics:
.usedOnHeapStorageMemory | Used on heap memory currently for storage, in bytes.
.usedOffHeapStorageMemory | Used off heap memory currently for storage, in bytes.
.totalOnHeapStorageMemory | Total available on heap memory for storage, in bytes. This amount can vary over time, on the MemoryManager implementation.
.totalOffHeapStorageMemory | Total available off heap memory for storage, in bytes. This amount can vary over time, depending on the MemoryManager implementation.
peakMemoryMetrics.* | Peak value of memory (and GC) metrics:
.JVMHeapMemory | Peak memory usage of the heap that is used for object allocation. The heap consists of one or more memory pools. The used and committed size of the returned memory usage is the sum of those values of all heap memory pools whereas the init and max size of the returned memory usage represents the setting of the heap memory which may not be the sum of those of all heap memory pools. The amount of used memory in the returned memory usage is the amount of memory occupied by both live objects and garbage objects that have not been collected, if any.
.JVMOffHeapMemory | Peak memory usage of non-heap memory that is used by the Java virtual machine. The non-heap memory consists of one or more memory pools. The used and committed size of the returned memory usage is the sum of those values of all non-heap memory pools whereas the init and max size of the returned memory usage represents the setting of the non-heap memory which may not be the sum of those of all non-heap memory pools.
.OnHeapExecutionMemory | Peak on heap execution memory in use, in bytes.
.OffHeapExecutionMemory | Peak off heap execution memory in use, in bytes.
.OnHeapStorageMemory | Peak on heap storage memory in use, in bytes.
.OffHeapStorageMemory | Peak off heap storage memory in use, in bytes.
.OnHeapUnifiedMemory | Peak on heap memory (execution and storage).
.OffHeapUnifiedMemory | Peak off heap memory (execution and storage).
.DirectPoolMemory | Peak memory that the JVM is using for direct buffer pool (java.lang.management.BufferPoolMXBean)
.MappedPoolMemory | Peak memory that the JVM is using for mapped buffer pool (java.lang.management.BufferPoolMXBean)
.ProcessTreeJVMVMemory | Virtual memory size in bytes. Enabled if spark.executor.processTreeMetrics.enabled is true.
.ProcessTreeJVMRSSMemory | Resident Set Size: number of pages the process has in real memory. This is just the pages which count toward text, data, or stack space. This does not include pages which have not been demand-loaded in, or which are swapped out. Enabled if spark.executor.processTreeMetrics.enabled is true.
.ProcessTreePythonVMemory | Virtual memory size for Python in bytes. Enabled if spark.executor.processTreeMetrics.enabled is true.
.ProcessTreePythonRSSMemory | Resident Set Size for Python. Enabled if spark.executor.processTreeMetrics.enabled is true.
.ProcessTreeOtherVMemory | Virtual memory size for other kind of process in bytes. Enabled if spark.executor.processTreeMetrics.enabled is true.
.ProcessTreeOtherRSSMemory | Resident Set Size for other kind of process. Enabled if spark.executor.processTreeMetrics.enabled is true.
.MinorGCCount | Total minor GC count. For example, the garbage collector is one of Copy, PS Scavenge, ParNew, G1 Young Generation and so on.
.MinorGCTime | Elapsed total minor GC time. The value is expressed in milliseconds.
.MajorGCCount | Total major GC count. For example, the garbage collector is one of MarkSweepCompact, PS MarkSweep, ConcurrentMarkSweep, G1 Old Generation and so on.
.MajorGCTime | Elapsed total major GC time. The value is expressed in milliseconds.

**Comment by Kdreamtomaster** [comment]
# 도커 컨테이너로 올렸을 경우 변경되는 부분

Docker 컨테이너로 Apache Spark, Apache Airflow, Apache Kafka, Prometheus, Grafana를 실행할 때의 설정 방법은 다음과 같습니다. 이 설정은 Kubernetes를 사용하지 않는 환경을 전제로 합니다.

## **1. Docker Compose 파일 작성**

각 서비스의 Docker 이미지를 정의하고, 필요한 설정을 포함하는 `docker-compose.yml` 파일을 작성합니다.

### **Spark**

- **Dockerfile과 설정 파일 준비**: Spark의 `metrics.properties`, `spark-env.sh`, `spark-defaults.conf` 등을 준비합니다.
- **Docker Compose 설정**: Spark 마스터와 워커 노드를 정의합니다.

```yaml
version: '3.7'
services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
```

### **Airflow**

- **StatsD Exporter 설정**: Airflow에서 StatsD 프로토콜을 통해 메트릭을 전송하고, 이를 Prometheus 형식으로 변환하기 위해 StatsD Exporter를 사용합니다.

```yaml
version: '3.7'
services:
  airflow-webserver:
    image: puckel/docker-airflow:latest
    environment:
      - AIRFLOW__METRICS__STATSD_ON=True
      - AIRFLOW__METRICS__STATSD_HOST=statsd-exporter
  statsd-exporter:
    image: prom/statsd-exporter
    ports:
      - "9102:9102"
```

### **Kafka**

- **JMX Exporter 설정**: Kafka에서 JMX Exporter를 사용하여 메트릭을 Prometheus에 노출합니다.

```yaml
version: '3.7'
services:
  kafka:
    image: wurstmeister/kafka
    environment:
      - KAFKA_OPTS=-javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
```

### **Prometheus 및 Grafana**

- **Prometheus 설정**: 각 서비스의 메트릭 엔드포인트를 스크랩하도록 `prometheus.yml` 파일을 준비합니다.

```yaml
version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
```

## **2. Prometheus 설정 파일 (`prometheus.yml`)**

각 서비스의 메트릭을 스크랩할 수 있도록 설정합니다.

```yaml
scrape_configs:
  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:8080', 'spark-worker:8081']

  - job_name: 'airflow'
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']
```

## **3. Grafana 대시보드 구성**

Grafana에 Prometheus를 데이터 소스로 추가한 후, 각 서비스에 맞는 대시보드를 구성합니다. Grafana UI를 통해 JSON 파일을 가져와서 대시보드를 쉽게 생성할 수 있습니다.

이러한 방식으로 Docker 컨테이너 환경에서 Spark, Airflow, Kafka의 메트릭을 Prometheus와 Grafana를 통해 모니터링할 수 있습니다. 이 설정은 Kubernetes 없이도 각 서비스의 성능과 상태를 효과적으로 추적할 수 있도록 해줍니다.

Citations:
[1] https://github.com/nikoshet/monitoring-spark-on-docker
[2] https://www.metricfire.com/blog/kafka-monitoring/
[3] https://www.redhat.com/en/blog/monitoring-apache-airflow-using-prometheus
[4] https://www.confluent.io/blog/monitor-kafka-clusters-with-prometheus-grafana-and-confluent/
[5] https://learn.microsoft.com/ko-kr/azure/synapse-analytics/spark/use-prometheus-grafana-to-monitor-apache-spark-application-level-metrics
[6] https://github.com/streamthoughts/kafka-monitoring-stack-docker-compose
